version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  allow:
    - dependency-type: direct
  cooldown:
    default-days: 3
  open-pull-requests-limit: 25

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  allow:
    - dependency-type: direct
  cooldown:
    default-days: 3
  open-pull-requests-limit: 25
