inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  Include:
    - "**/*.rb"
    - "**/*.rake"
    - "Gemfile"
    - "Rakefile"
    - "config.ru"
  Exclude:
    - "db/schema.rb"
    - "bin/**/*"
    - "vendor/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Include:
    - "**/*.rb"
    - "**/*.rake"
    - "Gemfile"
    - "Rakefile"
    - "config.ru"
